### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mntr31**
his real name is aryan, we both are doing this project together, but he don't know he can update his name in GitHub.

### CODE REVIEW

**Comment by andre1araujo** [comment]
Thank you very much for the update haha
Can I also include your name and github then?

**Comment by mntr31** [comment]
He did the main work, but thank you for asking. Don't need to add my name.

Though if you want to add custom dataset training of YOLOv3 then let me
know, I have tried it. most people have done it on COCO. It is not
implemented fully, but I know the flow now.

Also, thank you for your GitBook, it helped us a lot.

**Comment by andre1araujo** [comment]
Thank you and also I am glad the work was helpfull.
Can you elaborate on the custom dataset part? Did you use a different one than COCO? What classes did it detect?

**Comment by mntr31** [comment]
We didn't actually implemented it, but we guess hypothetically that it is
possible.

We went for 2 classes, fighter jets B2 and Rafal and we also started
training but the laptop didn't have GPU so it was taking too long for our
patience, so we dropped it then. It is also possible to train on Google
colab. After that we only need to change some parameters in the script
where we need to replace classes and number of classes with coco's data and
that should work if everything goes well.

**Comment by andre1araujo** [comment]
Ah nice.
I guess it would be a one class detector because it isn't suposed to see the B2 because it is a stealth bomber, isn't it? (that was a joke)
The GPU is always a problem, especially for more complex models. You could try something lighter like YOLOv3-Tiny whish should take less time and trials to train.
Any question you or Aryan may have, just feel free to ask!

**Comment by mntr31** [comment]
We have changed number of classes and class names in yolo_image.cpp, but it
still detects the older labels of COCO which we removed from the code to
keep our own labels, still.

**Comment by mntr31** [comment]
We implemented tiny yolo and it worked in first time at morning, now it is
not just working. We don't know why, we are getting the same gcc error in
all different datasets. We don't know why. Do you have any idea?

**Comment by andre1araujo** [comment]
Hi!
I don't know why the gcc error might be happening. Maybe it was due to the last modification you made on the c++ script. Before checking out what it says, try to delete the executable files (for example, one named "yolo" that is created after the gcc compilation) and delete the object files as well (the files in the objects folder). Then try to compile again with the Makefile.
Good luck!

**Pull request merged**
